# Docker Compose for BarberDemo
version: '3.8'

services:
  barberdemo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - SMTP_HOST=${SMTP_HOST:-}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER:-}
      - SMTP_PASS=${SMTP_PASS:-}
      - SMTP_FROM=${SMTP_FROM:-}
      - CALENDLY_USER_URL=${CALENDLY_USER_URL:-}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - barberdemo-network

  # PostgreSQL database (optional for future use)
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: barberdemo
  #     POSTGRES_USER: barberdemo
  #     POSTGRES_PASSWORD: ${DB_PASSWORD:-defaultpassword}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - barberdemo-network
  #   restart: unless-stopped

networks:
  barberdemo-network:
    driver: bridge

# volumes:
#   postgres_data:
#     driver: local
