name: .NET build & test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    - run: dotnet restore
    - run: dotnet build --configuration Release --no-restore
    - run: dotnet test  --configuration Release --no-build